spring:
  application:
    name: ${SERVER_NAME}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors: ## CORS Configuration
        cors-configurations:
          "[/**]": ## For all routes
            allowedOrigins: ${ALLOWED_ORIGINS} # With '*' we allow all origins. We can restrict by indicating domains or ip + port, e.g. http://localhost:3000 (where our front is, or a Vercel domain)
            allowedHeaders: "*" ## All headers allowed
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - PATCH

management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED}
  endpoints:
    web:
      exposure:
        include:
          - "*"

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    preferIpAddress: true
    hostname: ${SERVER_NAME}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_URL}
