spring:
  application:
    name: ${SERVER_NAME:ms-cloud-gateway}
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
      globalcors:
        cors-configurations:
          "[/**]":
            # Permitir SOLO los orígenes definidos en ALLOWED_ORIGINS.
            # Fallback seguro mientras desarrollas con Docker (front en 5050) o Vite (3000).
            allowedOrigins: ${ALLOWED_ORIGINS:http://localhost:5050,http://localhost:3000}
            allowedMethods: [GET, POST, PUT, DELETE, PATCH, OPTIONS]
            allowedHeaders: "*"
            allowCredentials: true
            maxAge: 3600
      routes:
        - id: eureka-ui
          uri: http://aws-eureka:8761
          predicates:
            - Path=/eureka/**
          filters:
            - StripPrefix=1

management:
  endpoint:
    gateway:
      enabled: ${ROUTE_TABLES_ENABLED:true}
  endpoints:
    web:
      exposure:
        include:
          - "*"

server:
  port: ${SERVER_PORT:8762}

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka}
  instance:
    prefer-ip-address: false
    hostname: ${SERVER_NAME:ms-cloud-gateway}
